# Generated by Django 3.1.6 on 2021-03-09 21:52

import ckeditor_uploader.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='دسته بندی')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='رنگ')),
                ('code', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر اصلی')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(verbose_name='موجودی')),
                ('minamount', models.IntegerField(verbose_name='حداقل موجودی')),
                ('variant', models.CharField(choices=[('None', 'ندارد'), ('Size', 'تنوع از نظر سایز'), ('Color', 'تنوع از نظر رنگ'), ('SizeColor', 'تنوع از نظر سایز و رنگ')], default='None', max_length=20, verbose_name='تنوع محصول')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='جزئیات')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرغعال')], max_length=20, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='سایز')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد سایز')),
            ],
            options={
                'verbose_name': 'اندازه_حجم',
                'verbose_name_plural': 'اندازه و حجم ها',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام')),
                ('image_id', models.IntegerField(blank=True, default=0, null=True, verbose_name='آی دی تصویر مورد نظر برای نمایش')),
                ('quantity', models.IntegerField(default=1, verbose_name='تعداد موجودی')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.color', verbose_name='رنگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size', verbose_name='سایز')),
            ],
            options={
                'verbose_name': 'نوع',
                'verbose_name_plural': 'انواع',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('comment', models.CharField(max_length=350, verbose_name='نظر')),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی پی')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('True', 'تایید'), ('False', 'عدم تایید')], default='New', max_length=20, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات مرتبط با محصولات',
            },
        ),
    ]
