# Generated by Django 3.1.6 on 2021-03-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210313_1805'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
