# Generated by Django 3.1.4 on 2020-12-15 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0009_auto_20201212_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('comment', models.CharField(max_length=350, verbose_name='نظر')),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی پی')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('True', 'تایید'), ('False', 'عدم تایید')], default='New', max_length=20, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
