# Generated by Django 3.1.6 on 2021-02-25 21:48

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210223_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'اندازه_حجم', 'verbose_name_plural': 'اندازه و حجم ها'},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name': 'نوع', 'verbose_name_plural': 'انواع'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AlterField(
            model_name='color',
            name='code',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='variants',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='آی دی تصویر مورد نظر برای نمایش'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='variants',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='تعداد موجودی'),
        ),
    ]
