# Generated by Django 3.1.6 on 2021-02-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210226_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='تصویر'),
        ),
    ]
