# Generated by Django 3.1.6 on 2021-04-19 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210418_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthit',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
    ]
