# Generated by Django 3.1.6 on 2021-04-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210419_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthit',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
