# Generated by Django 3.1.6 on 2021-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
