# Generated by Django 3.1.6 on 2021-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210419_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت فروش ویژه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت فروش عادی'),
        ),
    ]
