# Generated by Django 3.1.6 on 2021-04-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_specifications_specificationtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='specifications',
            options={'verbose_name': 'مشخصه', 'verbose_name_plural': 'مشخصات'},
        ),
        migrations.AlterModelOptions(
            name='specificationtype',
            options={'verbose_name': 'نوع مشخصه', 'verbose_name_plural': 'مشخصات'},
        ),
        migrations.AlterField(
            model_name='specifications',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.specificationtype', verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='specificationtype',
            name='name',
            field=models.CharField(max_length=65, verbose_name='نوع مشخصه'),
        ),
    ]
