# Generated by Django 3.1.6 on 2021-05-05 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210424_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آی پی', 'verbose_name_plural': 'آی پی بازدیدکنندگان'},
        ),
        migrations.AlterField(
            model_name='producthit',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ipaddress', verbose_name='آی پی آدرس'),
        ),
    ]
