# Generated by Django 3.1.6 on 2021-03-09 21:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=70, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=50, verbose_name='موضوع')),
                ('message', models.CharField(max_length=255, verbose_name='پیام')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='پاسخ')),
                ('ip', models.CharField(blank=True, max_length=20, verbose_name='آی پی')),
                ('status', models.CharField(choices=[('New', 'جدید'), ('Read', 'خوانده شده'), ('Closed', 'بسته')], default='New', max_length=30, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering_number', models.IntegerField()),
                ('question', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='پاسخ')),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرغعال')], max_length=20, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات پر تکرار',
                'ordering': ['ordering_number'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان وب سایت')),
                ('keywords', models.CharField(max_length=255, verbose_name='کلمات کلیدی')),
                ('description', models.CharField(max_length=255, verbose_name='عنوان')),
                ('company', models.CharField(blank=True, max_length=50, verbose_name='شرکت')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('fax', models.CharField(blank=True, max_length=20, verbose_name='فکس')),
                ('email', models.CharField(blank=True, max_length=70, verbose_name='ایمیل')),
                ('smtpserver', models.CharField(blank=True, max_length=20)),
                ('smtpemail', models.CharField(blank=True, max_length=50)),
                ('smtppassword', models.CharField(blank=True, max_length=50)),
                ('smtpport', models.CharField(blank=True, max_length=5)),
                ('icon', models.ImageField(blank=True, upload_to='images/', verbose_name='لوگو')),
                ('facecbook', models.CharField(blank=True, max_length=50, verbose_name='فیسبوک')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='اینستاگرام')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='تلگرام')),
                ('youtube', models.CharField(blank=True, max_length=50, verbose_name='یوتیوب')),
                ('twitter', models.CharField(blank=True, max_length=50, verbose_name='توییتر')),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='درباره ما')),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='تماس با ما')),
                ('worktime', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='ساعت کاری')),
                ('customerservices', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='خدمات مشتریان')),
                ('refrences', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.CharField(choices=[('True', 'فعال'), ('False', 'غیرغعال')], max_length=20, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'اطلاعات وب سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
