# Generated by Django 3.1.6 on 2021-04-24 09:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='refrences',
        ),
        migrations.AddField(
            model_name='setting',
            name='notices',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='اعلامیه وبسایت'),
        ),
    ]
