# Generated by Django 3.1.6 on 2021-04-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210424_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس ثابت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='تلفن همراه (جهت دریافت اطلاع رسانی پیامکی وبسایت)'),
        ),
    ]
