# Generated by Django 3.1.4 on 2020-12-11 19:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201204_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام ها'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'اطلاعات وب سایت', 'verbose_name_plural': 'اطلاعات سایت'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=70, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='آی پی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(blank=True, max_length=255, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='پاسخ'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('New', 'جدید'), ('Read', 'خوانده شده'), ('Closed', 'بسته')], default='New', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=50, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='درباره ما'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='شرکت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='تماس با ما'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='email',
            field=models.CharField(blank=True, max_length=70, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='facecbook',
            field=models.CharField(blank=True, max_length=50, verbose_name='فیسبوک'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='فکس'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='کلمات کلیدی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='status',
            field=models.CharField(choices=[('True', 'فعال'), ('False', 'غیرغعال')], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان وب سایت'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, verbose_name='توییتر'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='youtube',
            field=models.CharField(blank=True, max_length=50, verbose_name='یوتیوب'),
        ),
    ]
