# Generated by Django 3.1.6 on 2021-05-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_slidercontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slidercontent',
            options={'ordering': ['ordering_position'], 'verbose_name': 'اسلاید', 'verbose_name_plural': 'اسلایدر'},
        ),
    ]
