# Generated by Django 3.1.6 on 2021-05-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210503_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidercontent',
            name='image',
            field=models.ImageField(help_text='حداقل نسبت تصویر 2:1 می باشد - رزولوشن قابل قبول 400 * 1500', upload_to='images/', verbose_name='تصویر'),
        ),
    ]
