# Generated by Django 3.1.6 on 2021-02-23 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات پر تکرار'},
        ),
    ]
