# Generated by Django 3.1.6 on 2021-03-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210223_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['ordering_number'], 'verbose_name': 'سوال', 'verbose_name_plural': 'سوالات پر تکرار'},
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(max_length=255, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=50, verbose_name='موضوع'),
        ),
    ]
