# Generated by Django 3.1.6 on 2021-05-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210505_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('image', models.ImageField(help_text='این بنر در قسمت پایین صفحه اصلی سایت نمایش داده خواهد شد.', upload_to='images/', verbose_name='تصویر اصلی')),
                ('logo', models.ImageField(help_text='این تصویر به عنوان تصویری کوچک(لوگو) برروی تصویر اصلی نمایان خواهد شد.', upload_to='images/', verbose_name='تصویر کوچک')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('page_url', models.URLField(verbose_name='آدرس')),
                ('ordering_position', models.IntegerField(verbose_name='ترتیب نمایش بنر')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['ordering_position'],
            },
        ),
        migrations.CreateModel(
            name='BrandContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='توضیحات')),
                ('logo', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('status', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('page_url', models.URLField(verbose_name='آدرس')),
                ('ordering_position', models.IntegerField(verbose_name='ترتیب نمایش برند')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['ordering_position'],
            },
        ),
        migrations.AlterField(
            model_name='slidercontent',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='توضیحات'),
        ),
    ]
