# Generated by Django 3.1.6 on 2021-05-06 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210506_0425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercontent',
            name='logo',
        ),
    ]
