# Generated by Django 3.1.6 on 2021-05-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_bannercontent_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='smtpemail',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtppassword',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpport',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='smtpserver',
        ),
    ]
