# Generated by Django 3.1.6 on 2021-02-06 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='آدرس')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='شماره تماس')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=30, verbose_name='استان')),
                ('image', models.ImageField(blank=True, upload_to='images/users/', verbose_name='تصویر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاریر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
