# Generated by Django 3.1.6 on 2021-03-14 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210310_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_seller',
            new_name='is_sales_manager',
        ),
    ]
