# Generated by Django 3.1.6 on 2021-02-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210207_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='کدپستی'),
        ),
    ]
