# Generated by Django 3.1.6 on 2021-02-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, default=0, max_length=20, verbose_name='کدپستی'),
        ),
    ]
