# Generated by Django 3.1.6 on 2021-02-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210213_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
