# Generated by Django 3.1.6 on 2021-02-13 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210213_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='postal_code',
            new_name='postalcode',
        ),
    ]
