# Generated by Django 3.1.6 on 2021-04-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_comment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted'], 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=False, verbose_name='نمایش در سایت'),
        ),
    ]
