# Generated by Django 3.1.6 on 2021-03-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6, verbose_name='شماره سفارش')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('state', models.CharField(blank=True, max_length=30, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='شهر')),
                ('total', models.IntegerField(verbose_name='مجموع')),
                ('status', models.CharField(choices=[('New', 'درحال بررسی'), ('Accepted', 'تایید شده'), ('Preparing', 'درحال آماده سازی'), ('OnShipping', 'ارسال شده'), ('Completed', 'تکمیل شده'), ('Canceled', 'لغو شده'), ('Referred', 'مرجوع شده')], default='New', max_length=20, verbose_name='وضعیت سفارش')),
                ('postalcode', models.CharField(blank=True, max_length=20, verbose_name='کدپستی')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
                'ordering': ['status', '-create_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('amount', models.IntegerField(verbose_name='مجموع')),
                ('status', models.CharField(choices=[('New', 'درحال بررسی'), ('Accepted', 'تایید شده'), ('Canceled', 'لغو شده')], default='New', max_length=20, verbose_name='وضعیت سفارش')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد های خرید',
            },
        ),
    ]
