# Generated by Django 3.1.6 on 2021-02-12 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210127_1535'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_auto_20210206_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=6, verbose_name='شماره سفارش')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('state', models.CharField(blank=True, max_length=30, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='شهر')),
                ('total', models.FloatField(verbose_name='مجموع')),
                ('status', models.CharField(choices=[('New', 'درحال بررسی'), ('Accepted', 'تایید شده'), ('Preparing', 'درحال آماده سازی'), ('OnShipping', 'ارسال شده'), ('Completed', 'تکمیل شده'), ('Canceled', 'لغو شده'), ('Referred', 'مرجوع شده')], default='New', max_length=20, verbose_name='وضعیت سفارش')),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=100, verbose_name='یادداشت')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('price', models.FloatField(verbose_name='قیمت')),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'درحال بررسی'), ('Accepted', 'تایید شده'), ('Canceled', 'لغو شده')], default='New', max_length=20, verbose_name='وضعیت سفارش')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
