# Generated by Django 3.1.6 on 2021-02-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postalcode',
            field=models.CharField(blank=True, max_length=20, verbose_name='کدپستی'),
        ),
    ]
