# Generated by Django 3.1.6 on 2021-04-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210418_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
