# Generated by Django 3.1.6 on 2021-02-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_postalcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(verbose_name='مجموع'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
