# Generated by Django 3.1.6 on 2021-04-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20210418_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-create_at', 'status'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'محصول فروخته شده', 'verbose_name_plural': 'محصولات فروخته شده'},
        ),
        migrations.AlterModelOptions(
            name='shopcart',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبد های خرید تکمیل نشده'},
        ),
    ]
