# Generated by Django 3.1.6 on 2021-04-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210421_0958'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'محصول خریداری شده', 'verbose_name_plural': 'محصولات خریداری شده'},
        ),
    ]
