# Generated by Django 3.1.6 on 2021-03-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_orderproduct_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', '-create_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش ها'},
        ),
    ]
